"""Initial migration

Revision ID: cacf3cd39915
Revises: 
Create Date: 2025-09-24 23:40:17.981173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cacf3cd39915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_lng'), ['lng'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_street'), ['street'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('_security_answer_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_updated_at'), ['updated_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'ALERT', 'PARCEL_UPDATE', name='notification_type'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address_id', sa.UUID(), nullable=False),
    sa.Column('delivery_address_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='parcel_status'), nullable=False),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_delivery_address_id'), ['delivery_address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_estimated_delivery_date'), ['estimated_delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_pickup_address_id'), ['pickup_address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcels_tracking_id'), ['tracking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_parcels_updated_at'), ['updated_at'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='parcelstatus'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_parcel_id'), ['parcel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_status_history_status'))
        batch_op.drop_index(batch_op.f('ix_status_history_parcel_id'))
        batch_op.drop_index(batch_op.f('ix_status_history_actor_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_updated_at'))
        batch_op.drop_index(batch_op.f('ix_parcels_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_status'))
        batch_op.drop_index(batch_op.f('ix_parcels_pickup_address_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_estimated_delivery_date'))
        batch_op.drop_index(batch_op.f('ix_parcels_delivery_address_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_customer_id'))
        batch_op.drop_index(batch_op.f('ix_parcels_created_at'))

    op.drop_table('parcels')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_updated_at'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_street'))
        batch_op.drop_index(batch_op.f('ix_addresses_postal_code'))
        batch_op.drop_index(batch_op.f('ix_addresses_lng'))
        batch_op.drop_index(batch_op.f('ix_addresses_lat'))
        batch_op.drop_index(batch_op.f('ix_addresses_created_at'))
        batch_op.drop_index(batch_op.f('ix_addresses_county'))
        batch_op.drop_index(batch_op.f('ix_addresses_country'))
        batch_op.drop_index(batch_op.f('ix_addresses_city'))

    op.drop_table('addresses')
    # ### end Alembic commands ###
